#!/bin/bash

# This script echos the whole friggin path, because ls doesn't do it
# It also copies the result to the xclipboard
# Syntax: "path FILE", or "path PATTERN"
# Aaron White 2017

if [ "$#" -lt 1 ]; then # run with pwd
    # print output of pwd
    pwd
    # check if xclip is installed
    if [ $(command -v xclip) ]; then
        pwd | tr -d "\n" | xclip 
    fi
else
    # run with pattern
    for f in "$@"; do
        readlink -f $f 
        # check if xclip is installed
        if [ $(command -v xclip) ]; then
            readlink -f $f | tr -d "\n" | xclip
        fi
    done
fi


