#!/bin/bash

# Wrapper for default web-browser, epicially for launching from dmenu

# In 2018 I used chromium+vimium plugin. The downsides were: 
#   * Automatic updates (don't do that!)
#   * Vimium configuration seemed lacking
#   * No default homepage (what?)
#   * Chrome seemed resource intensive
# With these faults in mind, in 2019 I am trying out vimb, which had
# been installed for a while anyway

# export XDG_CONFIG_HOME=""

if [ "$#" -lt 1 ]; then # run with pwd
    vimb -c ${HOME}/.vimbrc &
else
    vimb $1 -c ${HOME}/.vimbrc &
fi

