#!/bin/bash
# shortcut for zipping directories as name.zip
# Aaron White 2018

# loop over inputs
for i in $@; do
	# remove trailing slashes
	target=${i%*/}
	target=${target%*/}
	target=${target%*/}

	echo "Zipping ${target} as ${target}.zip"
	rm -f ${target}.zip

	echo "zip -r ${target}.zip ${target}"
	zip -r ${target}.zip ${target}
done
